### ISSUE TITLE
not compatible with PHP7

### ISSUE THREAD

**Issue by joomlagate** [JoomGallery/JoomPlu#6]
When I running this plugin on PHP7, Joomla shows some warning message. 

It seems that this plugin is not compatible with PHP7.

Please update it to fix this.

Thank you.

**Comment by MrMusic** [comment]
This should be solved with PR https://github.com/JoomGallery/JoomPlu/pull/2
Can you confirm this fix?

**Comment by joomlagate** [comment]
Yes, it has been fixed by that PR #2.

Thank you.

**Comment by Chraneco** [comment]
Cool, thanks for the feedback!
